name: Cypress Tests e2e

on:
  push:
    branches:
      - 'main'
    workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out respository code
        uses: actions/checkout@v3

      - name: Run cypress tests with chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          browser: chrome
